title: Ghidra.js
email: little_scamp@yahoo.com
description: >
  Doing reverse engineering, low-level networking and other infosec stuff with JavaScript
baseurl: "/ghidra.js"
url: "http://vaguue.github.io"
github_username: vaguue

markdown: kramdown
permalink: /:year/:title:output_ext
